# Generated by Django 3.0.2 on 2020-04-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200430_0505'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='desc',
            field=models.CharField(default='', max_length=500),
        ),
    ]
