# Generated by Django 3.0.2 on 2020-05-02 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200501_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='desc',
        ),
    ]
