# Generated by Django 3.0.5 on 2020-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blogcommet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcommet',
            name='comment',
            field=models.TextField(default='', max_length=250),
        ),
    ]
