# Generated by Django 3.0.6 on 2021-05-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='github_url',
            field=models.URLField(default='https://github.com/'),
        ),
    ]
