# Generated by Django 3.0.5 on 2020-05-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200505_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
