# Generated by Django 3.0.6 on 2020-05-11 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blogpost_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
